Feature/hitobito 1956 js data sharing agreement
hitobito/hitobito_pbs pull request #249
Opened 2023-01-23 15:01 UTC by daniel-illi

2023-01-23 16:24 UTC, daniel-illi commented on app/models/pbs/event/restricted_role.rb
> +      role.participation.j_s_data_sharing_accepted = true if role.participation.j_s_data_sharing_acceptance_required?
macht das Sinn, das hier automatisch zu setzen?

2023-01-23 17:01 UTC, kronn requested changes

2023-01-24 21:37 UTC, daniel-illi commented on db/seeds/custom_contents.rb
> +
Korrekt :)

2023-01-24 21:37 UTC, daniel-illi commented on app/models/pbs/event/participation.rb.orig
> +>>>>>>> 93c6af5c (specs WIP)
:+1:

2023-01-30 09:10 UTC, merged